### ISSUE TITLE
CRC Error

### ISSUE THREAD

**Issue by nanderer** [gildas-lormeau/Polyglot-HTML-ZIP-PNG#1]
Hi,

i tested optipng on your demo at

https://raw.githubusercontent.com/gildas-lormeau/Polyglot-HTML-ZIP-PNG/main/demo.png.zip.html

the most fascinating thing that i found is that optipng didn't destroy the html part, its really good masked using this tEXtPNG thingy, quite fascinating` what you can do, but it showed a crc error:

```
$ optipng demo.png.zip.html 
** Processing: demo.png.zip.html
Warning: tEXt: CRC error
Warning: tEXt: CRC error
271x406 pixels, 8 bits/pixel, 255 colors in palette
Recoverable errors found in input. Rerun OptiPNG with -fix enabled.
Error: Previous error(s) not fixed

** Status report
1 file(s) have been processed.
1 error(s) have been encountered.
$ optipng demo.png.zip.html  --fix
** Processing: demo.png.zip.html
Warning: tEXt: CRC error
Warning: tEXt: CRC error
271x406 pixels, 8 bits/pixel, 255 colors in palette
Recoverable errors found in input. Fixing...
Input IDAT size = 10733 bytes
Input file size = 84292 bytes

Trying:
  zc = 9  zm = 8  zs = 0  f = 0		IDAT size = 11609
                               
Selecting parameters:
  zc = 9  zm = 8  zs = 0  f = 0		IDAT size = 11609

Output IDAT size = 11609 bytes (876 bytes increase)
Output file size = 85168 bytes (876 bytes = 1.04% increase)

** Status report
1 file(s) have been processed.
1 error(s) have been encountered.
1 erroneous file(s) have been fixed.
$ 
```

**Comment by gildas-lormeau** [comment]
Thank you very much for the info! I'll check it out as soon as I can. The `demo.png.zip.html` fle is also suferring from the same issue. The strange thing is that https://www.nayuki.io/page/png-file-chunk-inspector tells me that CRCs are OK (it displays a warning when they are not)...

EDIT: I have some doubts that https://www.nayuki.io/page/png-file-chunk-inspector really validates CRCs

**Comment by gildas-lormeau** [comment]
I'd be willing to bet it's related to a text encoding issue....

**Comment by gildas-lormeau** [comment]
In fact, the mistake was simpler than I guessed. Now the PNG file is valid.

**Comment by nayuki** [comment]
> EDIT: I have some doubts that https://www.nayuki.io/page/png-file-chunk-inspector really validates CRCs

It does validate CRCs strictly. It would be easy to test it yourself by opening a PNG file in a hex editor and altering a few bytes.

**Comment by gildas-lormeau** [comment]
> > EDIT: I have some doubts that https://www.nayuki.io/page/png-file-chunk-inspector really validates CRCs
> 
> It does validate CRCs strictly. It would be easy to test it yourself by opening a PNG file in a hex editor and altering a few bytes.

This is what I did with the corrupted and the fixed file yesterday but it was 2:00 AM, maybe I was too tired...

**Comment by gildas-lormeau** [comment]
For the record, I confirm that no warning messages are displayed when the CRC is wrong on https://www.nayuki.io/page/png-file-chunk-inspector unfortunately. See the screenshots below (done with the [old](https://github.com/gildas-lormeau/Polyglot-HTML-ZIP-PNG/raw/b502a9885d8cdafe47f5cbecd6086ef2e19e2d27/demo.png.zip.html) and [new](https://github.com/gildas-lormeau/Polyglot-HTML-ZIP-PNG/raw/main/demo.png.zip.html) demo files). I've sent an email to the author about this issue.

CRC OK:
![image](https://github.com/user-attachments/assets/0ad1cdba-d1d3-4c54-87cc-0e83c1f4b484)

Bad CRC:
![image](https://github.com/user-attachments/assets/d8c5da18-492d-4011-8b04-b6ac39b6d37b)

**Comment by nayuki** [comment]
I see that the humongous amount of `tEXt` is causing a visual overflow. Did you try scrolling the web page horizontally to the right?

**Comment by gildas-lormeau** [comment]
@nayuki Sorry for the inconvenience, I can confirm that all I had to do was scroll the page to the right. See the screenshot below. Thank you very much for your help :)

![image](https://github.com/user-attachments/assets/323b7548-735e-4986-bc63-d734e5b50f4c)

**Comment by nayuki** [comment]
@gildas-lormeau Thanks for your patience and understanding. With the help of your tricky test case, I went ahead and fixed the issue with "PNG file chunk inspector" for the long term. Now there are forced line breaks in any potentially long user-supplied text, which makes it far less likely for the rightmost column (error column) of the table to disappear.

**Comment by gildas-lormeau** [comment]
@nayuki I confirm your fix works perfectly, thank you very much!
